---
name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build doc
        run: |
          ansible-playbook ./ansible/omeroweb-install-doc.yml -i ./ansible/hosts/centos7-ice3.6 --extra-vars '{"clean": True, "web_session": True}'
          ansible-playbook ./ansible/omeroweb-install-doc.yml -i ./ansible/hosts/centos8-ice3.6 --extra-vars '{"clean": True, "web_session": True}'
          ansible-playbook ./ansible/omeroweb-install-doc.yml -i ./ansible/hosts/debian9-ice3.6 --extra-vars '{"clean": True, "web_session": True}'
          ansible-playbook ./ansible/omeroweb-install-doc.yml -i ./ansible/hosts/debian10-ice3.6 --extra-vars '{"clean": True, "web_session": True}'
          ansible-playbook ./ansible/omeroweb-install-doc.yml -i ./ansible/hosts/ubuntu1804-ice3.6 --extra-vars '{"clean": True, "web_session": True}'
          ansible-playbook ./ansible/omeroweb-install-doc.yml -i ./ansible/hosts/ubuntu2004-ice3.6 --extra-vars '{"clean": True, "web_session": True}'
      - name: Commit and push changes
        run: |
          mv ansible/doc docs
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git checkout ${GITHUB_REF##*/}
          git add -f docs/omeroweb-install-*
          git commit -m 'Update from CI'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/ome-documentation.git
          git push
