---
name: Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build doc
        run: |
          ansible-playbook ./ansible/omeroweb-install-doc.yml -i ./ansible/hosts/centos7-ice3.6 --extra-vars '{"clean": True, "web_session": True}'
      - name: Create doc branch
        run: |
          curl -XPOST -u "${{ secrets.API_TOKEN_GITHUB }}" \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -H "Content-Type: application/json" \
          https://api.github.com/repos/jburel/ome-documentation.git/dispatches \
          --data '{"event_type": "create_branch", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'", "branch_name": "test" }}' 