---
name: Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set branch name
        run: echo "branch_name="${{github.sha}}${GITHUB_REF##*/} >> $GITHUB_ENV
      - name: Create doc branch
        uses: peterjgrainger/action-create-branch@v2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: ${{ env.branch_name }}
      - name: Build doc
        run: |
          ansible-playbook ./ansible/omeroweb-install-doc.yml -i ./ansible/hosts/centos7-ice3.6 --extra-vars '{"clean": True, "web_session": True}'
      - name: Commit and push changes to the newly created branch
        run: |
          mv ansible/doc docs
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git pull origin ${{ env.branch_name }}
          git checkout ${{ env.branch_name }}
          git add -f docs/omeroweb-install-*
          git commit -m 'Update from CI'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git push
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          delete-branch: true
          base: master
          push-to-fork: ${{ github.actor }}/${{ github.repository }}
